const level1 = new Level([
    new ManZombie(),
    // new ManZombie(),
    // new ManZombie(),
    // new WildZombie(),
    // new WildZombie(),
    // new WildZombie(),
    // new WomanZombie(),
    // new WomanZombie(),
    // new WomanZombie(),
    // new Endboss(),
],
    [
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
    ],
    [
        new BackgroundObjectsFront('img/5_background/layers/Pale/groundFront.png', -719),
        new BackgroundObjectsFront('img/5_background/layers/Pale/cracks2.png', -719),

        new BackgroundObjectsFront('img/5_background/layers/Pale/groundFront.png', 0),
        new BackgroundObjectsFront('img/5_background/layers/Pale/cracks2.png', 0),

        new BackgroundObjectsFront('img/5_background/layers/Pale/groundFront.png', 719),
        new BackgroundObjectsFront('img/5_background/layers/Pale/cracks2.png', 719),

        new BackgroundObjectsFront('img/5_background/layers/Pale/groundFront.png', 719 * 2),
        new BackgroundObjectsFront('img/5_background/layers/Pale/cracks2.png', 719 * 2),

        new BackgroundObjectsFront('img/5_background/layers/Pale/groundFront.png', 719 * 3),
        new BackgroundObjectsFront('img/5_background/layers/Pale/cracks2.png', 719 * 3),
    ],
    [
        new BackgroundObjectsBack('img/5_background/layers/Pale/sky.png', -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses4.png',
            -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses3.png', -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses2.png', -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses1.png', -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/wall.png', -719),
        //ground
        new BackgroundObjectsBack('img/5_background/layers/Pale/groundBack.png', -719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/cracks1.png', -719),

        new BackgroundObjectsBack('img/5_background/layers/Pale/sky.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses4.png',
            0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses3.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses2.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses1.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/wall.png', 0),
        //ground
        new BackgroundObjectsBack('img/5_background/layers/Pale/groundBack.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/Pale/cracks1.png', 0),

        new BackgroundObjectsBack('img/5_background/layers/Pale/sky.png', 719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses4.png',
            719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses3.png', 719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses2.png', 719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses1.png', 719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/wall.png', 719),
        //ground
        new BackgroundObjectsBack('img/5_background/layers/Pale/groundBack.png', 719),
        new BackgroundObjectsBack('img/5_background/layers/Pale/cracks1.png', 719),

        new BackgroundObjectsBack('img/5_background/layers/Pale/sky.png', 719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses4.png',
            719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses3.png', 719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses2.png', 719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses1.png', 719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/wall.png', 719 * 2),
        //ground
        new BackgroundObjectsBack('img/5_background/layers/Pale/groundBack.png', 719 * 2),
        new BackgroundObjectsBack('img/5_background/layers/Pale/cracks1.png', 719 * 2),

        new BackgroundObjectsBack('img/5_background/layers/Pale/sky.png', 719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses4.png',
            719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses3.png', 719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses2.png', 719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/houses1.png', 719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/wall.png', 719 * 3),
        //ground
        new BackgroundObjectsBack('img/5_background/layers/Pale/groundBack.png', 719 * 3),
        new BackgroundObjectsBack('img/5_background/layers/Pale/cracks1.png', 719 * 3),
    ],
    [
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
    ],
    [
        new Sticks(),
        new Sticks(),
        new Sticks(),
        new Sticks(),
        new Sticks(),
    ],
);
