const level1 = new Level([
    new ManZombie(),
    new ManZombie(),
    new WomanZombie(),
    new WomanZombie(),
    new WomanZombie(),
    new WildZombie(),
    new WildZombie(),
    new WildZombie(),
],
    [
        new Endboss(),
    ],
    [
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsSmall(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
        new FogsBig(),
    ],
    [
        new BackgroundObjectsFront('img/5_background/layers/5/Ground.png', -718),
        new BackgroundObjectsFront('img/5_background/layers/5/Ground.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/5/Ground.png', 718),
        new BackgroundObjectsBack('img/5_background/layers/5/Ground.png', 718 * 2),
        new BackgroundObjectsBack('img/5_background/layers/5/Ground.png', 718 * 3),
        new BackgroundObjectsBack('img/5_background/layers/5/Ground.png', 718 * 4),
    ],
    [
        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', -718),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            -718),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', -718),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', -718),

        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            0),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', 0),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', 0),

        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', 718),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            718),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', 718),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', 718),

        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', 718 * 2),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            718 * 2),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', 718 * 2),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', 718 * 2),

        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', 718 * 3),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            718 * 3),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', 718 * 3),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', 718 * 3),

        new BackgroundObjectsBack('img/5_background/layers/1/Sky.png', 718 * 4),
        new BackgroundObjectsBack('img/5_background/layers/2/BG_Decor.png',
            718 * 4),
        new BackgroundObjectsBack('img/5_background/layers/3/Middle_Decor.png', 718 * 4),
        new BackgroundObjectsBack('img/5_background/layers/4/Foreground.png', 718 * 4),
    ],
    [
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
    ],
    [
        new Sticks(),
        new Sticks(),
        new Sticks(),
        new Sticks(),
        new Sticks(),
    ],
);
